config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"

  get "scoreboard" => "pages#scoreboard"
  get "rules" => "pages#rules"
  get "entries" => "pages#entries"
  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "form" => "pages#form"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def Home
  end

  def Scoreboard
  end

  def Entries
  end

  def Rules
  end

  def Form
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">
  
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active" .active></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div style="background:url(http://cdn3.vox-cdn.com/assets/4564579/Regional_blk.jpg) center center;
          background-size:cover;" class="slider-size">
      </div>
      <div class="carousel-caption">
      </div>
    </div>

    <div class="item">
      <div style="background:url(http://www.geeksandcleats.com/wp-content/uploads/2015/10/cam-superman-.jpg) center center;
          background-size:cover;" class="slider-size">
      </div>
      <div class="carousel-caption">
      </div>
    </div>

    <div class="item">
      <div style="background:url(http://sportsnaut.com/wp-content/uploads/2014/01/Peyton-Manning-Papa-Johns-Pizza.jpg) center center;
          background-size:cover;" class="slider-size">
      </div>
      <div class="carousel-caption">
      </div>
    </div>

  
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "The Prop Sheet", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Scoreboard", scoreboard_path %></li>
        <li><%= link_to "Entries", entries_path %></li>
        <li><%= link_to "Rules", rules_path %></li>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PropSheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
</head>
<body>

<%= render 'layouts/header' %>

<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/entries.html.erb
<div class='scoreboard'>
	
	<iframe width="1000" height="800" frameborder="0" src="https://docs.google.com/spreadsheets/d/1g1ZvM-Y36j0oT0um_erj09pU2nySxuWZ8eWt9sPwboU/pubhtml?gid=1025066011&amp;single=true&amp;widget=true&amp;headers=false"></iframe>
</div>

app/views/pages/form.html.erb
<div class='scoreboard'>
	<iframe src="https://docs.google.com/forms/d/1F-n6uEQEQUgnYCwLSTF3kfycfZcXTS8e-MFXpnpcOdE/viewform?embedded=true" width="760" height="1000" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>

app/views/pages/home.html.erb
<%= render 'layouts/carousel' %>


<div class='jumbotron center'>
	<h1>The Prop Sheet</h1>
	<p>Welcome to The Prop Sheet for Superbowl 50: Broncos Vs. Panthers</p>
    <p>
      <%= link_to "Learn More", rules_path , class: "btn btn-primary btn-lg" %> 
    </p>
</div>

app/views/pages/rules.html.erb
<div class="panel panel-default">
 <div class="panel-heading">Rules</div>
 <div class="panel-body">
   <ol>
   <li>Points will be collected by answering questions correctly.  There will be 1 pt, 2 pt, and 3pt questions specified on the form</li>
   <li> You must submit your form no later than 3:00 P.M on the day of the Super Bowl</li>
   <li> The tiebreaker is the closest guess to the total points scored in the Super Bowl</li>
   <li>If we cannot determine the answer to any of the questions, they will not be counted</li>
   <li> If there is no answer to a question, it will not be counted</li>
   <li>If the answer to a question is a push, it will not be counted</li>
 </div>
</div>

app/views/pages/scoreboard.html.erb
<div class='scoreboard'>
	<iframe width="580" height="800" frameborder="0" src="https://docs.google.com/spreadsheets/d/1g1ZvM-Y36j0oT0um_erj09pU2nySxuWZ8eWt9sPwboU/pubhtml?gid=1414531453&amp;single=true&amp;widget=true&amp;headers=false"></iframe>
</div>